# Generated by Django 4.2.2 on 2023-06-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(db_column='titulo', max_length=100)),
                ('descripcion', models.TextField(db_column='descripcion', max_length=1000)),
                ('autor', models.CharField(db_column='autor', max_length=100)),
                ('anio', models.IntegerField(db_column='anio', default=2000)),
            ],
        ),
    ]
