# Generated by Django 4.2.2 on 2023-06-29 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(db_column='rol', max_length=100)),
                ('direccion', models.CharField(db_column='direccion', max_length=100)),
                ('rut', models.CharField(db_column='rut', default='11.111.111-1', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
                ('direccion', models.CharField(db_column='direccion', max_length=100)),
                ('fono', models.CharField(db_column='fono', default='+5695555555', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='documento',
            name='descripcion',
            field=models.CharField(db_column='descripcion', max_length=100),
        ),
    ]
